=== gustavogiao/XML_XSD-lab/extra/estudo1/festival.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="festival">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="nome" type="xs:string"/>
        <xs:element name="local" type="xs:string"/>
        <xs:element name="ano">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1800"/>
                    <xs:maxInclusive value="2026"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>        
        <xs:element name="filmes">
          <xs:complexType>
            <xs:sequence>
              
              <xs:element name="filme" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo" type="xs:string"/>
                    <xs:element name="realizador" type="xs:string"/>
                    <xs:element name="duracao" type="xs:int"/>
                    
                    <xs:element name="sessoes">
                      <xs:complexType>
                        <xs:sequence>
                          
                          <xs:element name="sessao" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="data" type="xs:string"/>
                                <xs:element name="hora" type="xs:string"/>
                                <xs:element name="sala" type="xs:string"/>
                              </xs:sequence>
                              <xs:attribute name="id" type="xs:int" use="required"/>
                            </xs:complexType>
                          </xs:element>
                          
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    
                  </xs:sequence>
                  <xs:attribute name="codigo" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/estudo1/festival.xml
<?xml version="1.0" encoding="UTF-8"?>

<festival
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="festival.xsd">

<nome>Os Mais Pesados da Capital</nome>
<local>Lisboa, MEO Arena</local>
<ano>2026</ano>

<filmes>
    <filme codigo="FESTIVAL-4321">
        <titulo>Cona</titulo>
        <realizador>John B.</realizador>
        <duracao>35</duracao>
        <sessoes>
            <sessao id="1">
                <data>08-05-2026</data>
                <hora>18</hora>
                <sala>25</sala>
            </sessao>
            <sessao id="2">
                <data>07-05-2026</data>
                <hora>18</hora>
                <sala>25</sala>
            </sessao>
        </sessoes>
    </filme>
    <filme codigo="FESTIVAL-3232">
        <titulo>Cona II</titulo>
        <realizador>John B.</realizador>
        <duracao>35</duracao>
        <sessoes>
            <sessao id="1">
                <data>10-05-2026</data>
                <hora>12</hora>
                <sala>25</sala>
            </sessao>
            <sessao id="2">
                <data>11-05-2026</data>
                <hora>17</hora>
                <sala>25</sala>
            </sessao>
        </sessoes>
    </filme>
</filmes>

</festival>
