=== gustavogiao/XML_XSD-lab/ex2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="authors">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="publisher" type="xs:string"/>
                            <xs:element name="year">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1000"/>
                                        <xs:maxInclusive value="2100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="characteristics">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cover">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Hardcover"/>
                                                    <xs:enumeration value="Paperback"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="number_of_pages">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="index">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="chapter" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="title" type="xs:string"/>
                                                    <xs:element name="page">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:integer">
                                                                    <xs:minInclusive value="1"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/xml_worksheet/ex2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="../xsl_worksheet/ex1/book.xsl"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ex2.xsd">

    <book>
        <title>Livro Random</title>

        <authors>
            <author>Cristiano Ronaldo</author>
            <author>Francisco Trincão</author>
        </authors>

        <publisher>Random Publisher</publisher>
        <year>2024</year>

        <characteristics>
            <cover>Hardcover</cover>
            <number_of_pages>200</number_of_pages>
        </characteristics>

        <index>
            <chapter>
                <title>Chapter 1</title>
                <page>1</page>
            </chapter>
            <chapter>
                <title>Chapter 2</title>
                <page>15</page>
            </chapter>
        </index>

    </book>

    <book>
        <title>Livro Random 2</title>

        <authors>
            <author>Messi</author>
            <author>Neymar</author>
        </authors>

        <publisher>Random Publisher 2</publisher>
        <year>2023</year>

        <characteristics>
            <cover>Paperback</cover>
            <number_of_pages>300</number_of_pages>
        </characteristics>

        <index>
            <chapter>
                <title>Chapter 1</title>
                <page>1</page>
            </chapter>
            <chapter>
                <title>Chapter 2</title>
                <page>20</page>
            </chapter>
        </index>

    </book>

</catalog>
