=== gustavogiao/XML_XSD-lab/ex8.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="subject">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="attendance_sheet" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="date" type="xs:date"/>
                            <xs:element name="start_time" type="xs:dateTime"/>
                            <xs:element name="end_time" type="xs:dateTime"/>

                            <xs:element name="students">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="student" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="number" type="xs:integer"/>
                                                    <xs:element name="name" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="present" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="yes"/>
                                                            <xs:enumeration value="no"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/xml_worksheet/ex8.xml
<?xml version="1.0" encoding="UTF-8" ?>
<subject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ex8.xsd">
    <name>Tecnologias de Integração</name>
    <attendance_sheet>
        <date>2026-03-10</date>
        <start_time>2026-03-10T09:00:00</start_time>
        <end_time>2026-03-10T11:00:00</end_time>

        <students>
            <student present="yes">
                <number>131231</number>
                <name>Gustavo</name>
            </student>
            <student present="yes">
                <number>42343</number>
                <name>João</name>
            </student>
        </students>
    </attendance_sheet>
</subject>
