=== gustavogiao/XML_XSD-lab/extra/estudo6/cinema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="generoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ACAO"/>
            <xs:enumeration value="COMEDIA"/>
            <xs:enumeration value="DRAMA"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="filmeType">
        <xs:sequence>
            <xs:element name="titulo" type="xs:string"/>
            <xs:element name="duracao" type="xs:int"/>
            <xs:element name="classificacao" type="xs:float"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="genero" type="generoType" use="required"/>
    </xs:complexType>

    <xs:element name="cinema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="filme" type="filmeType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/estudo6/cinema.xml
<?xml version="1.0" encoding="UTF-8"?>

<cinema
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="cinema.xsd">
    <filme id="1" genero="COMEDIA">
        <titulo>Cão de Caça</titulo>
        <duracao>90</duracao>
        <classificacao>5.0</classificacao>
    </filme>
    <filme id="2" genero="ACAO">
        <titulo>Ratmir, o Rei</titulo>
        <duracao>25</duracao>
        <classificacao>3.8</classificacao>
    </filme>
</cinema>
