=== gustavogiao/XML_XSD-lab/extra/ex3/ex3.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<?xml-stylesheet type="text/xsl" href="ex3.xsl"?>

<xs:element name="company">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="info">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="founded">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                        <xs:attribute name="year">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1800"/>
                                                    <xs:maxInclusive value="2026"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="active" type="xs:boolean"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="departments">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="department" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="name" type="xs:string"/>
                                    <xs:element name="employees">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="employee" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="name" type="xs:string"/>
                                                            <xs:element name="age">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:integer">
                                                                        <xs:minInclusive value="0"/>
                                                                        <xs:maxInclusive value="66"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:element>
                                                            <xs:element name="salary">
                                                                <xs:complexType>
                                                                    <xs:simpleContent>
                                                                        <xs:extension base="xs:decimal">
                                                                            <xs:attribute name="currency">
                                                                                <xs:simpleType>
                                                                                    <xs:restriction base="xs:string">
                                                                                        <xs:enumeration value="EUR"/>
                                                                                        <xs:enumeration value="DOL"/>
                                                                                        <xs:enumeration value="REAL"/>
                                                                                    </xs:restriction>
                                                                                </xs:simpleType>
                                                                            </xs:attribute>
                                                                        </xs:extension>
                                                                    </xs:simpleContent>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="contact">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="email" type="xs:string"/>
                                                                        <xs:element name="phone" type="xs:string"/>
                                                                    </xs:sequence>
                                                                </xs:complexType>
                                                            </xs:element>
                                                            <xs:element name="skills">
                                                                <xs:complexType>
                                                                    <xs:sequence>
                                                                        <xs:element name="skill" maxOccurs="unbounded" type="xs:string"/>
                                                                    </xs:sequence>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                        <xs:attribute name="id" type="xs:string"/>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:string"/>
                                <xs:attribute name="type" type="xs:string"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="notes"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/ex3/ex3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Exemplo completo de XML -->

<?xml-stylesheet type="text/xsl" href="ex3.xsl"?>

<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ex3.xsd">

    <!-- Informação da empresa -->
    <info>
        <name>Tech Solutions</name>
        <founded year="2010">Portugal</founded>
        <active>true</active>
    </info>

    <!-- Lista de departamentos -->
    <departments>

        <department id="D01" type="IT">

            <name>Development</name>

            <!-- Lista de funcionários -->
            <employees>

                <employee id="E01">

                    <name>Gustavo</name>
                    <age>22</age>
                    <salary currency="EUR">1200.50</salary>

                    <!-- contacto -->
                    <contact>
                        <email>gustavo@email.com</email>
                        <phone>(+351) 999999999</phone>
                    </contact>

                    <!-- lista (repetição) -->
                    <skills>
                        <skill>Java</skill>
                        <skill>XML</skill>
                        <skill>SQL</skill>
                    </skills>

                </employee>

                <employee id="E02">

                    <name>Ana</name>
                    <age>25</age>
                    <salary currency="EUR">1500.00</salary>

                    <contact>
                        <email>ana@email.com</email>
                        <phone>(+351) 888888888</phone>
                    </contact>

                    <skills>
                        <skill>Python</skill>
                        <skill>Data Analysis</skill>
                    </skills>

                </employee>

            </employees>

        </department>

        <department id="D02" type="HR">

            <name>Human Resources</name>

            <employees>
                <employee id="E03">
                    <name>Maria</name>
                    <age>30</age>
                    <salary currency="EUR">1100</salary>

                    <contact>
                        <email>maria@email.com</email>
                        <phone>(+351) 777777777</phone>
                    </contact>

                    <skills>
                        <skill>Communication</skill>
                        <skill>Recruitment</skill>
                    </skills>

                </employee>
            </employees>

        </department>

    </departments>

    <!-- Elemento vazio -->
    <notes/>

</company>
