=== gustavogiao/XML_XSD-lab/extra/estudo7/estudo7.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="academia">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="curso" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string"/>
                            <xs:element name="area" type="xs:string"/>
                            <xs:element name="duracao" type="xs:int"/>

                            <xs:element name="formadores">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="formador" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nome" type="xs:string"/>
                                                    <xs:element name="email" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                        <xs:attribute name="estado">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="ATIVO"/>
                                    <xs:enumeration value="INATIVO"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/estudo7/estudo7.xml
<?xml version="1.0" encoding="UTF-8"?>

<academia
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="estudo7.xsd">
    <curso codigo="CN-TI" estado="ATIVO">
        <nome>Tecnologias de Informação</nome>
        <area>Área: Informática</area>
        <duracao>3</duracao>

        <formadores>
            <formador id="1">
                <nome>Fábio Marques</nome>
                <email>fabio@ua.pt</email>
            </formador>
            <formador id="2">
                <nome>Joaquim Ferreira</nome>
                <email>jjfc@ua.pt</email>
            </formador>
        </formadores>
    </curso>

    <curso codigo="CN-EI" estado="ATIVO">
        <nome>Engenharia Informática</nome>
        <area>Área: Informática</area>
        <duracao>3</duracao>

        <formadores>
            <formador id="1">
                <nome>Fábio Marques</nome>
                <email>fabio@ua.pt</email>
            </formador>
            <formador id="2">
                <nome>Joaquim Ferreira</nome>
                <email>jjfc@ua.pt</email>
            </formador>
        </formadores>
    </curso>

</academia>
