=== gustavogiao/XML_XSD-lab/extra/ex1/cursos_online.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="platform">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="course" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="year">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="2000"/>
                                    <xs:maxInclusive value="2100"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="modules">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="module" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="name" type="xs:string"/>
                                                <xs:element name="duration">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="1"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="students">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="student" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="name" type="xs:string"/>
                                                <xs:element name="grade">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="0"/>
                                                            <xs:maxInclusive value="20"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                            <xs:attribute name="id" type="xs:string"/>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string"/>
                    <xs:attribute name="level">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="beginner"/>
                                <xs:enumeration value="advanced"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/ex1/cursos_online.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cursos_online.xsl"?>

<platform xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="cursos_online.xsd">

    <course id="C01" level="beginner">

        <title>XML Fundamentals</title>
        <year>2026</year>

        <modules>
            <module>
                <name>Introduction</name>
                <duration>2</duration>
            </module>

            <module>
                <name>XSD</name>
                <duration>3</duration>
            </module>
        </modules>

        <students>
            <student id="S01">
                <name>Gustavo</name>
                <grade>20</grade>
            </student>
            <student id="S02">
                <name>Ratmir</name>
                <grade>20</grade>
            </student>
        </students>

    </course>

    <course id="C02" level="advanced">

        <title>XSLT Mastery</title>
        <year>2026</year>

        <modules>
            <module>
                <name>XSL Basics</name>
                <duration>4</duration>
            </module>
        </modules>

        <students>
            <student id="S03">
                <name>Maria</name>
                <grade>20</grade>
            </student>
        </students>

    </course>

</platform>
