=== gustavogiao/XML_XSD-lab/xsl_worksheet/ex2/ex2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bank_transactions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="transaction" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="date" type="xs:date"/>

                            <xs:element name="source_account">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bank" type="xs:string"/>
                                        <xs:element name="account_number">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>


                            <xs:element name="destination_account">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bank" type="xs:string"/>
                                        <xs:element name="account_number">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="amount">
                                <xs:complexType>
                                    <xs:simpleContent>

                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="currency" type="xs:string" use="required"/>
                                        </xs:extension>

                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="description" type="xs:string"/>

                        </xs:sequence>

                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:minInclusive value="1"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/xsl_worksheet/ex2/ex2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="ex2.xsl"?>
<bank_transactions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ex2.xsd">
    <transaction id="43">
        <date>2026-03-06</date>
        <source_account>
            <bank>BPI</bank>
            <account_number>123254</account_number>
        </source_account>
        <destination_account>
            <bank>BPI</bank>
            <account_number>123232</account_number>
        </destination_account>
        <amount currency="EUR">15000</amount>
        <description>Invoice Payment</description>
    </transaction>
</bank_transactions>
