=== gustavogiao/XML_XSD-lab/extra/ex2/encomendas.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="orders">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="order" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="customer">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="name" type="xs:string"></xs:element>
                                    <xs:element name="email" type="xs:string"></xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="items">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="item" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="name" type="xs:string"></xs:element>
                                                <xs:element name="quantity">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="0"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                                <xs:element name="price">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:double">
                                                            <xs:minInclusive value="0"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="date" type="xs:date"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string"/>
                    <xs:attribute name="status">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="pending"></xs:enumeration>
                                <xs:enumeration value="completed"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/ex2/encomendas.xml
<?xml version="1.0" encoding="UTF-8"?>

<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="encomendas.xsd">
        
    <order id="001" status="completed">

        <customer>
            <name>Gustavo</name>
            <email>gustavo@email.com</email>
        </customer>

        <items>
            <item>
                <name>Portátil</name>
                <quantity>1</quantity>
                <price>1200</price>
            </item>
            <item>
                <name>Mouse</name>
                <quantity>1</quantity>
                <price>100</price>
            </item>
        </items>

        <date>2026-04-11</date>

    </order>

    <order id="002" status="pending">

        <customer>
            <name>Ana</name>
            <email>ana@email.com</email>
        </customer>

        <items>
            <item>
                <name>Keyboard</name>
                <quantity>1</quantity>
                <price>50</price>
            </item>
        </items>

        <date>2026-04-11</date>

    </order>

</orders>
