=== gustavogiao/XML_XSD-lab/xml_worksheet/ex9.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="invoice">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="number">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="date" type="xs:date"/>
                <xs:element name="seller">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="purchaser">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="bill">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="qty">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="unit_price">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="amount">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="total">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/xml_worksheet/ex9.xml
<?xml version="1.0" encoding="UTF-8" ?>
<invoice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="ex9.xsd">

    <number>321321</number>
    <date>2025-01-15</date>
    <seller>
        <name>Gustavo Gião</name>
        <address>Street Example 32..43</address>
    </seller>
    <purchaser>
        <name>John Doe</name>
        <address>Street Example 43.1323</address>
    </purchaser>
    <bill>
        <item>
            <qty>1</qty>
            <description>Produto bonito nao sei que</description>
            <unit_price>5.00</unit_price>
            <amount>5.00</amount>
        </item>
        <item>
            <qty>1</qty>
            <description>Sopa de Coentros</description>
            <unit_price>5.00</unit_price>
            <amount>5.00</amount>
        </item>
        <total>10</total>
    </bill>
</invoice>
