=== gustavogiao/XML_XSD-lab/xsl_worksheet/ex3/ex3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="publisher">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="books">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="book">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="subtitle" type="xs:string"/>
                                        <xs:element name="year">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="1000"/>
                                                    <xs:maxInclusive value="2100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="authors">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="index">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="chapter" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="title" type="xs:string"/>
                                                                <xs:element name="page">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:integer">
                                                                            <xs:minInclusive value="1"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/xsl_worksheet/ex3/ex3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="ex3.xsl"?>
<publisher xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="ex3.xsd">
    <books>
        <book id="BOOK01">
            <title>Titulo de teste</title>
            <subtitle>Subtitulo de Teste</subtitle>
            <year>2026</year>
            <authors>
                <author>Gustavo</author>
            </authors>
            <index>
                <chapter>
                    <title>Chapter 1</title>
                    <page>1</page>
                </chapter>
                <chapter>
                    <title>Chapter 2</title>
                    <page>3</page>
                </chapter>
            </index>
        </book>
    </books>
</publisher>
