=== gustavogiao/XML_XSD-lab/extra/exame_recurso/ex1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="orders">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="customer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="contactName" type="xs:string"/>
                            <xs:element name="phone" type="xs:string"/>
                            <xs:element name="ordersList">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="order" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="employeeID">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:integer">
                                                                <xs:minInclusive value="1"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="orderDate" type="xs:dateTime"/>
                                                    <xs:element name="country" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== gustavogiao/XML_XSD-lab/extra/exame_recurso/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="ex1.xsl"?>

<orders
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ex1.xsd">

    <customer>
        <name>Great Lakes Food Market</name>
        <contactName>Howard Snyder</contactName>
        <phone>(503) 555-7555</phone>

        <ordersList>
            <order>
                <employeeID>6</employeeID>
                <orderDate>1997-05-06T00:00:00</orderDate>
                <country>USA</country>
            </order>

            <order>
                <employeeID>8</employeeID>
                <orderDate>1997-07-04T00:00:00</orderDate>
                <country>USA</country>
            </order>

            <order>
                <employeeID>1</employeeID>
                <orderDate>1997-07-31T00:00:00</orderDate>
                <country>USA</country>
            </order>
        </ordersList>

    </customer>

</orders>
